pcre2_error: split compile_error_texts to make it C99 compliant
C99 requires that the compiler support string literals up to 4096
characters.

Split the single long string into a small array, while at it add
instructions to aid with maintenance and renumber comments in the
compile_error_texts elements to map better with the error codes
they represent.